### ISSUE TITLE
Interaction Reponse Messages need to inherit from RestUserMessage

### ISSUE THREAD

**Issue by CAVX** [Discord-Net-Labs/Discord.Net-Labs#109]
When retrieving an interaction response message, key functionality is not included due to the fact that these messages come in as a RestSystemMessage, rather than a RestUserMessage.

In my example, I'm trying to retrieve an interaction response using the `ReactionAdded` event and then get the embed from it.

```csharp
    public void Initialize()
    {
        _discord.ReactionAdded += HandleReactionAsync;
    }

    private Task HandleReactionAsync(Cacheable<IUserMessage, ulong> messageCache, Cacheable<IMessageChannel, ulong> channelCache, SocketReaction reaction)
    {
        _ = Task.Run(async () =>
        {
            var message = await messageCache.GetOrDownloadAsync(); //does not pull interaction responses because they don't inherit IUserMessage
            if (await channelCache.GetOrDownloadAsync() is not ITextChannel channel)
                return;

            if (reaction.User.IsSpecified && reaction.User.Value.IsBot)
                return;

            await ParseEmbedAsync(message, channel, true);

        });
        return Task.CompletedTask;
    }
```

Since the interaction response doesn't inherit from `IUserMessage`, the response isn't retrieved at all, even though the `ReactionAdded` event was triggered and it's a valid message to react to (not ephemeral, etc.).

If you then try to retrieve it manually instead:
```csharp
    IMessage workaround;
    if (message != null)
        workaround = message;
    else
        workaround = await channel.GetMessageAsync(messageCache.Id, CacheMode.AllowDownload);    // <----    Pulling the message manually as a workaround.
```

Most of the message metadata is empty, including embeds, which I needed. This is because `RestMessage.Create` instantiates the message as a `RestSystemMessage`, not a `RestUserMessage`. The embeds, as well as all other user message data, *do* already come in from the `Model` object returned from the API.

If interaction messages inherited from `RestUserMessage`, these problems would both be fixed, as `RestUserMessage.Create` populates the necessary data. With my very limited understanding of the code, I assume that in `RestMessage.Create`, models with the type of `MessageType.ApplicationCommand` should return as `RestUserMessage`, not `RestSystemMessage`.

**Comment by quinchs** [comment]
Fixed in [6b36285](https://github.com/Discord-Net-Labs/Discord.Net-Labs/commit/6b36285053133d110ab09f20fdee15ca99f4735e). Will close when pushed to nuget

**Comment by CAVX** [comment]
I'm still seeing this issue in certain cases. I think it's because `RestMessage` also needs the same fix applied.
